### PR TITLE
FIX DRA ClaimInfo and Manager unit tests

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fixes ClaimInfo unit tests

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
Thanks! Let's merge when all tests in that directory are done. Otherwise it's harder to verify that the proposed changes work (one has to delete `manager_test.go` first).

**Comment by bart0sh** [comment]
ok, i'll add manager test fixes to this PR.

**Comment by bart0sh** [comment]
@pohly Now both tests are passing. PTAL

```
go test -coverprofile=/tmp/vscode-goOct5aM/go-code-cover k8s.io/kubernetes/pkg/kubelet/cm/dra

ok  	k8s.io/kubernetes/pkg/kubelet/cm/dra	0.426s	coverage: 79.8% of statements
```

**Review by pohly — APPROVED** [review]
Thanks, will merge.

**Pull request merged**
