### PR TITLE
dra e2e enhancements

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

Test on multiple nodes, ensure that NodeUnprepareResource got called.

/assign @bart0sh 

We could merge this now, but I still intend to add more tests for different nodes.

### CODE REVIEW

**Comment by pohly** [comment]
@bart0sh I can't reproduce on my machine that NodeUnprepareResource doesn't get called because the pods get force-deleted.

Does the new check fail for you? If yes, does this patch fix it?
```patch
diff --git a/test/e2e/dra/dra.go b/test/e2e/dra/dra.go
index fd54d3dea51..51971d2ae99 100644
--- a/test/e2e/dra/dra.go
+++ b/test/e2e/dra/dra.go
@@ -251,8 +251,21 @@ func (b *builder) resourceClaimParameters() *corev1.ConfigMap {
 func (b *builder) pod() *corev1.Pod {
        pod := e2epod.MakePod(b.f.Namespace.Name, nil, nil, false, "env && sleep 100000")
        pod.Spec.RestartPolicy = corev1.RestartPolicyNever
-       var zero int64
-       pod.Spec.TerminationGracePeriodSeconds = &zero
+       // Let kubelet kill the pods quickly. Setting
+       // TerminationGracePeriodSeconds to zero would bypass kubelet
+       // completely because then the apiserver enables a force-delete even
+       // when DeleteOptions for the pod don't ask for it (see
+       // https://github.com/kubernetes/kubernetes/blob/0f582f7c3f504e807550310d00f130cb5c18c0c3/pkg/registry/core/pod/strategy.go#L151-L171).
+       //
+       // We don't do that because it breaks tracking of claim usage: the
+       // kube-controller-manager assumes that kubelet is done with the pod
+       // once it got removed or has a grace period of 0. Setting the grace
+       // period to zero directly in DeletionOptions or indirectly through
+       // TerminationGracePeriodSeconds causes the controller to remove
+       // the pod from ReservedFor before it actually has stopped on
+       // the node.
+       one := int64(1)
+       pod.Spec.TerminationGracePeriodSeconds = &one
        pod.ObjectMeta.GenerateName = ""
        b.podCounter++
        pod.ObjectMeta.Name = fmt.Sprintf("tester-%d", b.podCounter)
```

**Comment by bart0sh** [comment]
@pohly let me check on your rebased branch. Are you done with the rebase?

**Comment by bart0sh** [comment]
> I can't reproduce on my machine that NodeUnprepareResource doesn't get called because the pods get force-deleted.

You can easily see it by grep-ing kubelet log and listing /var/run/cdi.
Here is how it looks in my setup:
```
$ grep 'syncTerminatedPod enter' /tmp/kubelet.log
I0919 16:10:11.501499   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-9067/dra-test-driver-9l62k" podUID=f7722d15-5837-4788-84b8-8e188364d48b
I0919 16:10:11.503622   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-9067/tester-3" podUID=3a447dbc-f8f9-40f6-9f72-6d14bf100265
I0919 16:10:11.505952   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-9067/tester-2" podUID=588abd4d-f024-496f-8d69-08f3f69cfa31
I0919 16:10:12.514546   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-9067/tester-1" podUID=d2b0050a-87ba-4453-8470-00a65138712a
I0919 16:10:24.564020   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-3192/tester-1" podUID=291c05d2-9123-4125-850a-4f7a862506b7
I0919 16:10:28.576836   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-3192/tester-2" podUID=caf022f6-df87-458c-bfcd-efa243bd4cd1
I0919 16:10:33.592343   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-3192/tester-3" podUID=e9b85895-9e8d-4a20-adf0-259d44e84605
I0919 16:10:35.600089   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-3192/dra-test-driver-htjgh" podUID=25c4dd20-38af-4d9e-ba9c-f53fd84d3932
I0919 16:10:45.647805   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-8728/tester-4" podUID=65e3d2dc-f391-4941-a5f8-5e9fe4febf16
I0919 16:10:45.647834   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-8728/tester-6" podUID=3eb277f7-5de1-4cf0-85e9-be0a31c3ce5f
I0919 16:10:45.647926   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-8728/dra-test-driver-pvx8c" podUID=9ad1d52a-67c3-4a2a-a841-d4c7ad5e2707
I0919 16:10:46.656395   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-8728/tester-5" podUID=dfe82118-23e4-45c1-9e85-34b9cbb5097d
I0919 16:10:54.688272   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-2041/dra-test-driver-httcm" podUID=14b9f621-0557-4d17-bda2-5745cc4315f1
I0919 16:10:56.699478   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-2041/tester-7" podUID=b7575e53-ab3f-4b36-a637-1f91aaf805e4
I0919 16:11:07.736119   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-1563/tester-8" podUID=8e42a2cb-5433-4aad-8b22-fdb66f8eeb0d
I0919 16:11:07.738627   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-1563/dra-test-driver-xj9n6" podUID=775b106d-e88f-4647-8413-d9fe34373845
I0919 16:11:16.770916   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-4697/dra-test-driver-z9f4r" podUID=42552590-cf16-41a3-9341-a30da34308e6
I0919 16:11:17.779314   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-4697/tester-9" podUID=8c58ced1-14aa-4ea4-a6aa-eee9abe0efb7
I0919 16:11:27.809182   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-6785/dra-test-driver-tlfnq" podUID=2c38fc2c-aae2-44ec-b5ae-d28bc9d24229
I0919 16:11:29.822563   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-6785/tester-4" podUID=e261a26a-fb0a-4079-8789-16ef55b7cb5f
I0919 16:11:36.853268   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-594/dra-test-driver-kq7tk" podUID=6841fcc7-747a-4206-9a64-b613190090e7
I0919 16:11:36.856784   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-594/tester-12" podUID=ef37e414-abad-46a1-ad14-33f7b8831edf
I0919 16:11:37.865878   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-594/tester-10" podUID=427187a0-725b-4e84-8f3f-13e3d7b1199c
I0919 16:11:38.876396   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-594/tester-11" podUID=15532f47-9046-4d00-8db7-9c6e4e3b5da9
I0919 16:11:41.887865   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-319/dra-test-driver-vzs44" podUID=4acff840-e750-4919-bde8-163cfd52c98d
I0919 16:11:52.928263   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-6596/dra-test-driver-lhv5c" podUID=ec8ccf55-8dc0-4944-a474-a02ee341b699
I0919 16:11:54.940172   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-6596/tester-13" podUID=2ad1b491-8352-4a96-a685-9a93d545075c
I0919 16:12:01.967335   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-4150/dra-test-driver-5d94k" podUID=a7a4be36-7186-4574-9e07-ede76fcbcb44
I0919 16:12:02.977211   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-4150/tester-14" podUID=721d1636-7e43-4ab3-89dc-b5bf41a36751
I0919 16:12:11.007901   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-6755/dra-test-driver-88zcs" podUID=064bcc4d-c493-4abd-a04d-7e937d7a1215
I0919 16:12:13.019078   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-6755/tester-15" podUID=23a30e41-f4e3-464d-92db-5fc6a5c258e0
```

You can see that in some cases driver pod terminates before the test pods, which practically means that UnprepareResource  can't be called.

/var/run/cdi should be empty at the end of test runs. If you remove all .json files from there and run full dra test suite and then list /var/run/cdi again you'll most probably see something like this:
```
$ ls -la /var/run/cdi/
total 44
drwxrwxrwx  2 ed   root 260 syys  19 16:12 .
drwxr-xr-x 39 root root 900 syys  19 15:45 ..
-rw-r--r--  1 root root 176 syys  19 16:11 dra-1563.k8s.io-f05bd1ba-0590-4fdd-8d50-0fec1a9e4d0e.json
-rw-r--r--  1 root root 176 syys  19 16:10 dra-2041.k8s.io-ad4ac151-66ee-468f-bbc0-78d0be0528ee.json
-rw-r--r--  1 root root 176 syys  19 16:11 dra-4150.k8s.io-ba621145-56c7-44c9-86ad-91093d233b6b.json
-rw-r--r--  1 root root 176 syys  19 16:11 dra-4697.k8s.io-006453b0-0850-49d0-b227-cc0e8b2d471f.json
-rw-r--r--  1 root root 175 syys  19 16:11 dra-594.k8s.io-bcb8700b-878f-4713-a347-338cf8224e81.json
-rw-r--r--  1 root root 176 syys  19 16:11 dra-6596.k8s.io-a8fb22ff-145b-4cb4-82bc-f594ddd8cea5.json
-rw-r--r--  1 root root 176 syys  19 16:12 dra-6755.k8s.io-1577a506-7cac-4eb8-8aac-2bda129ef6db.json
-rw-r--r--  1 root root 176 syys  19 16:11 dra-6785.k8s.io-0ca2c591-4f09-405a-ae11-1790ae4b5342.json
-rw-r--r--  1 root root 176 syys  19 16:10 dra-8728.k8s.io-336e85f2-b772-466c-ba99-ae1a1e7ab2a9.json
-rw-r--r--  1 root root 176 syys  19 16:12 dra-8800.k8s.io-a3b133b8-9842-40d0-9232-bcebfd549018.json
-rw-r--r--  1 root root 176 syys  19 16:10 dra-9067.k8s.io-4ca109c2-26ed-4984-9da7-ed0577a5d060.json
```

which also suggests that UnprepareResource was not called and therefore wasn't able to remove cdi files.

Can you confirm that you can see a similar picture in your setup?
```

**Comment by bart0sh** [comment]
@pohly your change fixes the issue in my setup.

**Comment by bart0sh** [comment]
> Force-deletion of a pod doesn't wait for kubelet. This can break the E2E tests
because the test pods get removed from the apiserver immediately, followed by
deleting the driver pods

This is not what I see on my system. Here is an example when driver pod termination starts *before* the test pod termination:
```
I0919 16:10:45.647805   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-8728/tester-4" podUID=65e3d2dc-f391-4941-a5f8-5e9fe4febf16
I0919 16:10:45.647834   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-8728/tester-6" podUID=3eb277f7-5de1-4cf0-85e9-be0a31c3ce5f
I0919 16:10:45.647926   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-8728/dra-test-driver-pvx8c" podUID=9ad1d52a-67c3-4a2a-a841-d4c7ad5e2707
I0919 16:10:46.656395   32362 kubelet.go:1866] "syncTerminatedPod enter" pod="dra-8728/tester-5" podUID=dfe82118-23e4-45c1-9e85-34b9cbb5097d
```

**Comment by pohly** [comment]
> This is not what I see on my system. Here is an example when driver pod termination starts before the test pod termination:

The order in which kubelet sees the deletion is random. What I meant is that the tests proceeds with deleting the driver pods directly after deleting the test pods, without waiting in the middle.

**Comment by pohly** [comment]
> You can easily see it by grep-ing kubelet log and listing /var/run/cdi.

We can't do that in the e2e test, but checking the prepared resources now catches that, doesn't it?

Anyway, I've updated this PR and it is ready for review. The extended tests with multiple nodes revealed an issue in the scheduler (nil map access).

**Comment by bart0sh** [comment]
> We can't do that in the e2e test, but checking the prepared resources now catches that, doesn't it?

yes, it should catch it. I was just wondering if you can reproduce the issue on your setup.

**Review by bart0sh — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
Manually cherry-picked and squashed into the rebased dynamic-resource-allocation branch.

**Pull request closed without merging**
