### PR TITLE
Fix UnprepareResources idempotence bug

### PR DESCRIPTION
**Pull request by bart0sh**

### CODE REVIEW

**Review by klueska — COMMENTED** [review]
Can you expand the comment above the call to remove the pod from the claimInfo object explaining that this may be called against pods that no longer exist in the cache and why that is OK / desired.

**Comment by bart0sh** [comment]
@klueska done. Let me know if you want me to rephrase it.

**Comment by klueska** [comment]
Actually, I take it back, I think the comment there is fine, i.e.
```
		// Delete pod UID from the cache
		claimInfo.deletePodReference(pod.UID)
```
But let's add a comment on this function as:
```
// UnprepareResources calls a plugin's NodeUnprepareResource API for each resource claim owned by a pod.
// This function is idempotent and may be called multiple times against the same pod.
// As such, calls to the underlying NodeUnprepareResource API are skipped for claims that have already been successfully unprepared.
func (m *ManagerImpl) UnprepareResources(pod *v1.Pod) error {
```

**Comment by bart0sh** [comment]
done

**Comment by pohly** [comment]
Merged manually.

**Pull request closed without merging**
