### PR TITLE
dra kubelet: fix plugin and state tests

### PR DESCRIPTION
**Pull request by oxxenix**

### CODE REVIEW

**Comment by oxxenix** [comment]
@pohly, PTAL

**Comment by pohly** [comment]
Looks okay. Can you finish the rest of `pkg/kubelet/cm/dra/...`?

**Comment by oxxenix** [comment]
@pohly, all tests are working now, PTAL
```=== RUN   TestNewClaimInfoFromClaim
=== RUN   TestNewClaimInfoFromClaim/successfully_created_object
=== RUN   TestNewClaimInfoFromClaim/successfully_created_object_with_empty_allocation
--- PASS: TestNewClaimInfoFromClaim (0.00s)
    --- PASS: TestNewClaimInfoFromClaim/successfully_created_object (0.00s)
    --- PASS: TestNewClaimInfoFromClaim/successfully_created_object_with_empty_allocation (0.00s)
=== RUN   TestNewClaimInfoFromState
=== RUN   TestNewClaimInfoFromState/successfully_created_object
--- PASS: TestNewClaimInfoFromState (0.00s)
    --- PASS: TestNewClaimInfoFromState/successfully_created_object (0.00s)
=== RUN   TestClaimInfoSetCDIDevices
=== RUN   TestClaimInfoSetCDIDevices/add_new_device
=== RUN   TestClaimInfoSetCDIDevices/replace_existing_device
=== RUN   TestClaimInfoSetCDIDevices/empty_list_of_devices
--- PASS: TestClaimInfoSetCDIDevices (0.00s)
    --- PASS: TestClaimInfoSetCDIDevices/add_new_device (0.00s)
    --- PASS: TestClaimInfoSetCDIDevices/replace_existing_device (0.00s)
    --- PASS: TestClaimInfoSetCDIDevices/empty_list_of_devices (0.00s)
=== RUN   TestClaimInfoAddPodReference
=== RUN   TestClaimInfoAddPodReference/empty_PodUIDs_list
=== RUN   TestClaimInfoAddPodReference/first_pod_reference
=== RUN   TestClaimInfoAddPodReference/second_pod_reference
--- PASS: TestClaimInfoAddPodReference (0.00s)
    --- PASS: TestClaimInfoAddPodReference/empty_PodUIDs_list (0.00s)
    --- PASS: TestClaimInfoAddPodReference/first_pod_reference (0.00s)
    --- PASS: TestClaimInfoAddPodReference/second_pod_reference (0.00s)
=== RUN   TestClaimInfoHasPodReference
=== RUN   TestClaimInfoHasPodReference/claim_doesn't_reference_pod
=== RUN   TestClaimInfoHasPodReference/claim_references_pod
=== RUN   TestClaimInfoHasPodReference/empty_claim_info
--- PASS: TestClaimInfoHasPodReference (0.00s)
    --- PASS: TestClaimInfoHasPodReference/claim_doesn't_reference_pod (0.00s)
    --- PASS: TestClaimInfoHasPodReference/claim_references_pod (0.00s)
    --- PASS: TestClaimInfoHasPodReference/empty_claim_info (0.00s)
=== RUN   TestClaimInfoDeletePodReference
=== RUN   TestClaimInfoDeletePodReference/claim_doesn't_reference_pod
=== RUN   TestClaimInfoDeletePodReference/claim_references_pod
=== RUN   TestClaimInfoDeletePodReference/empty_claim_info
--- PASS: TestClaimInfoDeletePodReference (0.00s)
    --- PASS: TestClaimInfoDeletePodReference/claim_doesn't_reference_pod (0.00s)
    --- PASS: TestClaimInfoDeletePodReference/claim_references_pod (0.00s)
    --- PASS: TestClaimInfoDeletePodReference/empty_claim_info (0.00s)
=== RUN   TestClaimInfoSetPrepared
=== RUN   TestClaimInfoSetPrepared/claim_info_is_not_prepared
=== RUN   TestClaimInfoSetPrepared/claim_info_is_prepared
=== RUN   TestClaimInfoSetPrepared/empty_claim_info
--- PASS: TestClaimInfoSetPrepared (0.00s)
    --- PASS: TestClaimInfoSetPrepared/claim_info_is_not_prepared (0.00s)
    --- PASS: TestClaimInfoSetPrepared/claim_info_is_prepared (0.00s)
    --- PASS: TestClaimInfoSetPrepared/empty_claim_info (0.00s)
=== RUN   TestClaimInfoIsPrepared
=== RUN   TestClaimInfoIsPrepared/claim_info_is_not_prepared
=== RUN   TestClaimInfoIsPrepared/claim_info_is_prepared
=== RUN   TestClaimInfoIsPrepared/empty_claim_info
--- PASS: TestClaimInfoIsPrepared (0.00s)
    --- PASS: TestClaimInfoIsPrepared/claim_info_is_not_prepared (0.00s)
    --- PASS: TestClaimInfoIsPrepared/claim_info_is_prepared (0.00s)
    --- PASS: TestClaimInfoIsPrepared/empty_claim_info (0.00s)
=== RUN   TestNewClaimInfoCache
=== RUN   TestNewClaimInfoCache/successfully_created_cache
=== RUN   TestNewClaimInfoCache/empty_parameters
=== RUN   TestNewClaimInfoCache/empty_checkpoint_name
=== RUN   TestNewClaimInfoCache/incorrect_checkpoint_name
--- PASS: TestNewClaimInfoCache (0.01s)
    --- PASS: TestNewClaimInfoCache/successfully_created_cache (0.01s)
    --- PASS: TestNewClaimInfoCache/empty_parameters (0.00s)
    --- PASS: TestNewClaimInfoCache/empty_checkpoint_name (0.00s)
    --- PASS: TestNewClaimInfoCache/incorrect_checkpoint_name (0.00s)
=== RUN   TestClaimInfoCacheWithLock
=== RUN   TestClaimInfoCacheWithLock/cache_is_locked_inside_a_function
=== RUN   TestClaimInfoCacheWithLock/cache_is_Rlocked_inside_a_function
=== RUN   TestClaimInfoCacheWithLock/successfully_called_function
=== RUN   TestClaimInfoCacheWithLock/erroring_function
--- PASS: TestClaimInfoCacheWithLock (0.01s)
    --- PASS: TestClaimInfoCacheWithLock/cache_is_locked_inside_a_function (0.00s)
    --- PASS: TestClaimInfoCacheWithLock/cache_is_Rlocked_inside_a_function (0.00s)
    --- PASS: TestClaimInfoCacheWithLock/successfully_called_function (0.00s)
    --- PASS: TestClaimInfoCacheWithLock/erroring_function (0.00s)
=== RUN   TestClaimInfoCacheWithRLock
=== RUN   TestClaimInfoCacheWithRLock/RLock-ed_cache_allows_another_RLock
=== RUN   TestClaimInfoCacheWithRLock/cache_is_locked_inside_a_function
=== RUN   TestClaimInfoCacheWithRLock/successfully_called_function
=== RUN   TestClaimInfoCacheWithRLock/erroring_function
--- PASS: TestClaimInfoCacheWithRLock (0.01s)
    --- PASS: TestClaimInfoCacheWithRLock/RLock-ed_cache_allows_another_RLock (0.00s)
    --- PASS: TestClaimInfoCacheWithRLock/cache_is_locked_inside_a_function (0.00s)
    --- PASS: TestClaimInfoCacheWithRLock/successfully_called_function (0.00s)
    --- PASS: TestClaimInfoCacheWithRLock/erroring_function (0.00s)
=== RUN   TestClaimInfoCacheAdd
=== RUN   TestClaimInfoCacheAdd/claimInfo_successfully_added
--- PASS: TestClaimInfoCacheAdd (0.00s)
    --- PASS: TestClaimInfoCacheAdd/claimInfo_successfully_added (0.00s)
=== RUN   TestClaimInfoCacheContains
=== RUN   TestClaimInfoCacheContains/cache_hit
=== RUN   TestClaimInfoCacheContains/cache_miss
=== RUN   TestClaimInfoCacheContains/cache_miss:_empty_cache_and_empty_claim_info
--- PASS: TestClaimInfoCacheContains (0.00s)
    --- PASS: TestClaimInfoCacheContains/cache_hit (0.00s)
    --- PASS: TestClaimInfoCacheContains/cache_miss (0.00s)
    --- PASS: TestClaimInfoCacheContains/cache_miss:_empty_cache_and_empty_claim_info (0.00s)
=== RUN   TestClaimInfoCacheGet
=== RUN   TestClaimInfoCacheGet/cache_hit
=== RUN   TestClaimInfoCacheGet/cache_miss
--- PASS: TestClaimInfoCacheGet (0.00s)
    --- PASS: TestClaimInfoCacheGet/cache_hit (0.00s)
    --- PASS: TestClaimInfoCacheGet/cache_miss (0.00s)
=== RUN   TestClaimInfoCacheDelete
=== RUN   TestClaimInfoCacheDelete/item_in_cache
=== RUN   TestClaimInfoCacheDelete/item_not_in_cache
--- PASS: TestClaimInfoCacheDelete (0.00s)
    --- PASS: TestClaimInfoCacheDelete/item_in_cache (0.00s)
    --- PASS: TestClaimInfoCacheDelete/item_not_in_cache (0.00s)
=== RUN   TestClaimInfoCacheHasPodReference
=== RUN   TestClaimInfoCacheHasPodReference/uid_is_referenced
=== RUN   TestClaimInfoCacheHasPodReference/uid_is_not_referenced
--- PASS: TestClaimInfoCacheHasPodReference (0.00s)
    --- PASS: TestClaimInfoCacheHasPodReference/uid_is_referenced (0.00s)
    --- PASS: TestClaimInfoCacheHasPodReference/uid_is_not_referenced (0.00s)
=== RUN   TestSyncToCheckpoint
=== RUN   TestSyncToCheckpoint/successfully_checkpointed_cache
--- PASS: TestSyncToCheckpoint (0.00s)
    --- PASS: TestSyncToCheckpoint/successfully_checkpointed_cache (0.00s)
=== RUN   TestNewManagerImpl
=== RUN   TestNewManagerImpl/invalid_directory_path
=== RUN   TestNewManagerImpl/valid_directory_path
--- PASS: TestNewManagerImpl (0.00s)
    --- PASS: TestNewManagerImpl/invalid_directory_path (0.00s)
    --- PASS: TestNewManagerImpl/valid_directory_path (0.00s)
=== RUN   TestGetResources
=== RUN   TestGetResources/claim_info_with_devices
=== RUN   TestGetResources/nil_claiminfo
--- PASS: TestGetResources (0.01s)
    --- PASS: TestGetResources/claim_info_with_devices (0.00s)
    --- PASS: TestGetResources/nil_claiminfo (0.00s)
=== RUN   TestPrepareResources
=== RUN   TestPrepareResources/claim_doesn't_exist
=== RUN   TestPrepareResources/unknown_driver
=== RUN   TestPrepareResources/should_prepare_resources,_driver_returns_nil_value
=== RUN   TestPrepareResources/driver_returns_empty_result
=== RUN   TestPrepareResources/pod_is_not_allowed_to_use_resource_claim
=== RUN   TestPrepareResources/no_container_uses_the_claim
=== RUN   TestPrepareResources/resource_already_prepared
=== RUN   TestPrepareResources/should_timeout
=== RUN   TestPrepareResources/should_prepare_resource,_claim_not_in_cache
=== RUN   TestPrepareResources/resource_already_prepared#01
--- PASS: TestPrepareResources (0.07s)
    --- PASS: TestPrepareResources/claim_doesn't_exist (0.00s)
    --- PASS: TestPrepareResources/unknown_driver (0.00s)
    --- PASS: TestPrepareResources/should_prepare_resources,_driver_returns_nil_value (0.01s)
    --- PASS: TestPrepareResources/driver_returns_empty_result (0.00s)
    --- PASS: TestPrepareResources/pod_is_not_allowed_to_use_resource_claim (0.00s)
    --- PASS: TestPrepareResources/no_container_uses_the_claim (0.01s)
    --- PASS: TestPrepareResources/resource_already_prepared (0.01s)
    --- PASS: TestPrepareResources/should_timeout (0.02s)
    --- PASS: TestPrepareResources/should_prepare_resource,_claim_not_in_cache (0.01s)
    --- PASS: TestPrepareResources/resource_already_prepared#01 (0.00s)
=== RUN   TestUnprepareResources
=== RUN   TestUnprepareResources/unknown_driver
=== RUN   TestUnprepareResources/resource_claim_referenced_by_other_pod(s)
=== RUN   TestUnprepareResources/should_timeout
=== RUN   TestUnprepareResources/should_fail_when_driver_returns_empty_response
=== RUN   TestUnprepareResources/should_unprepare_resource
=== RUN   TestUnprepareResources/should_unprepare_already_prepared_resource
=== RUN   TestUnprepareResources/should_unprepare_resource_when_driver_returns_nil_value
--- PASS: TestUnprepareResources (0.05s)
    --- PASS: TestUnprepareResources/unknown_driver (0.00s)
    --- PASS: TestUnprepareResources/resource_claim_referenced_by_other_pod(s) (0.00s)
    --- PASS: TestUnprepareResources/should_timeout (0.02s)
    --- PASS: TestUnprepareResources/should_fail_when_driver_returns_empty_response (0.00s)
    --- PASS: TestUnprepareResources/should_unprepare_resource (0.01s)
    --- PASS: TestUnprepareResources/should_unprepare_already_prepared_resource (0.01s)
    --- PASS: TestUnprepareResources/should_unprepare_resource_when_driver_returns_nil_value (0.00s)
=== RUN   TestPodMightNeedToUnprepareResources
--- PASS: TestPodMightNeedToUnprepareResources (0.00s)
=== RUN   TestGetContainerClaimInfos
=== RUN   TestGetContainerClaimInfos/should_get_claim_info
=== RUN   TestGetContainerClaimInfos/should_fail_when_claim_info_not_found
=== RUN   TestGetContainerClaimInfos/should_fail_when_none_of_the_supported_fields_are_set
=== RUN   TestGetContainerClaimInfos/should_fail_when_claim_info_is_not_cached
--- PASS: TestGetContainerClaimInfos (0.01s)
    --- PASS: TestGetContainerClaimInfos/should_get_claim_info (0.00s)
    --- PASS: TestGetContainerClaimInfos/should_fail_when_claim_info_not_found (0.00s)
    --- PASS: TestGetContainerClaimInfos/should_fail_when_none_of_the_supported_fields_are_set (0.00s)
    --- PASS: TestGetContainerClaimInfos/should_fail_when_claim_info_is_not_cached (0.00s)
=== RUN   TestParallelPrepareUnprepareResources
--- PASS: TestParallelPrepareUnprepareResources (0.18s)
PASS
ok      k8s.io/kubernetes/pkg/kubelet/cm/dra    0.410s
=== RUN   TestGRPCConnIsReused
    client.go:78: I0708 14:53:04.047203] Creating new gRPC connection protocol="unix" endpoint="/tmp/dra_plugin1312540678/server.sock"
I0708 14:53:04.047996  358290 client.go:107] "Calling NodePrepareResources rpc" request="&NodePrepareResourcesRequest{Claims:[]*Claim{&Claim{Namespace:dummy-namespace,Uid:dummy-uid,Name:dummy-claim,},},}"
I0708 14:53:04.048050  358290 client.go:119] "Done calling NodePrepareResources rpc" response="nil" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
I0708 14:53:04.048108  358290 client.go:107] "Calling NodePrepareResources rpc" request="&NodePrepareResourcesRequest{Claims:[]*Claim{&Claim{Namespace:dummy-namespace,Uid:dummy-uid,Name:dummy-claim,},},}"
I0708 14:53:04.048167  358290 client.go:119] "Done calling NodePrepareResources rpc" response="nil" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
--- PASS: TestGRPCConnIsReused (0.00s)
=== RUN   TestNewDRAPluginClient
=== RUN   TestNewDRAPluginClient/plugin_name_is_empty
=== RUN   TestNewDRAPluginClient/plugin_name_not_found_in_the_list
=== RUN   TestNewDRAPluginClient/plugin_exists
--- PASS: TestNewDRAPluginClient (0.00s)
    --- PASS: TestNewDRAPluginClient/plugin_name_is_empty (0.00s)
    --- PASS: TestNewDRAPluginClient/plugin_name_not_found_in_the_list (0.00s)
    --- PASS: TestNewDRAPluginClient/plugin_exists (0.00s)
=== RUN   TestNodeUnprepareResources
=== RUN   TestNodeUnprepareResources/server_supports_v1alpha4
    client.go:78: I0708 14:53:04.048857] Creating new gRPC connection protocol="unix" endpoint="/tmp/dra_plugin1444172769/server.sock"
I0708 14:53:04.049461  358290 client.go:129] "Calling NodeUnprepareResource rpc" request="&NodeUnprepareResourcesRequest{Claims:[]*Claim{},}"
I0708 14:53:04.051900  358290 client.go:141] "Done calling NodeUnprepareResources rpc" response="&NodeUnprepareResourcesResponse{Claims:map[string]*NodeUnprepareResourceResponse{},}" err=null
--- PASS: TestNodeUnprepareResources (0.00s)
    --- PASS: TestNodeUnprepareResources/server_supports_v1alpha4 (0.00s)
=== RUN   TestRegistrationHandler_ValidatePlugin
=== RUN   TestRegistrationHandler_ValidatePlugin/no_versions_provided
I0708 14:53:04.052157  358290 plugin.go:220] "Validate DRA plugin" name="" endpoint="" versions=""
=== RUN   TestRegistrationHandler_ValidatePlugin/unsupported_version
I0708 14:53:04.052208  358290 plugin.go:220] "Validate DRA plugin" name="" endpoint="" versions="v2.0.0"
=== RUN   TestRegistrationHandler_ValidatePlugin/plugin_already_registered_with_a_higher_supported_version
I0708 14:53:04.052317  358290 plugin.go:138] "Register new DRA plugin" logger="DRA registration handler" pluginName="this-plugin-already-exists-and-has-a-long-name-so-it-doesnt-collide" endpoint=""
I0708 14:53:04.052338  358290 plugin.go:220] "Validate DRA plugin" name="this-plugin-already-exists-and-has-a-long-name-so-it-doesnt-collide" endpoint="" versions="v1.0.0"
=== RUN   TestRegistrationHandler_ValidatePlugin/should_validate_the_plugin
I0708 14:53:04.052428  358290 plugin.go:220] "Validate DRA plugin" name="this-is-a-dummy-plugin-with-a-long-name-so-it-doesnt-collide" endpoint="" versions="v1.3.0"
I0708 14:53:04.052467  358290 plugin.go:203] "Deregister DRA plugin" logger="DRA registration handler" pluginName="this-plugin-already-exists-and-has-a-long-name-so-it-doesnt-collide" endpoint=""
I0708 14:53:04.052484  358290 plugin.go:214] "Deregister DRA plugin not necessary, was already removed" logger="DRA registration handler"
--- PASS: TestRegistrationHandler_ValidatePlugin (0.00s)
    --- PASS: TestRegistrationHandler_ValidatePlugin/no_versions_provided (0.00s)
    --- PASS: TestRegistrationHandler_ValidatePlugin/unsupported_version (0.00s)
    --- PASS: TestRegistrationHandler_ValidatePlugin/plugin_already_registered_with_a_higher_supported_version (0.00s)
    --- PASS: TestRegistrationHandler_ValidatePlugin/should_validate_the_plugin (0.00s)
PASS
ok      k8s.io/kubernetes/pkg/kubelet/cm/dra/plugin     0.024s
=== RUN   TestCheckpointGetOrCreate
=== RUN   TestCheckpointGetOrCreate/Create_non-existing_checkpoint
=== RUN   TestCheckpointGetOrCreate/Restore_checkpoint_-_single_claim
=== RUN   TestCheckpointGetOrCreate/Restore_checkpoint_-_single_claim_-_multiple_devices
=== RUN   TestCheckpointGetOrCreate/Restore_checkpoint_-_multiple_claims
=== RUN   TestCheckpointGetOrCreate/Restore_checkpoint_-_invalid_checksum
=== RUN   TestCheckpointGetOrCreate/Restore_checkpoint_with_invalid_JSON
--- PASS: TestCheckpointGetOrCreate (0.01s)
    --- PASS: TestCheckpointGetOrCreate/Create_non-existing_checkpoint (0.00s)
    --- PASS: TestCheckpointGetOrCreate/Restore_checkpoint_-_single_claim (0.00s)
    --- PASS: TestCheckpointGetOrCreate/Restore_checkpoint_-_single_claim_-_multiple_devices (0.00s)
    --- PASS: TestCheckpointGetOrCreate/Restore_checkpoint_-_multiple_claims (0.00s)
    --- PASS: TestCheckpointGetOrCreate/Restore_checkpoint_-_invalid_checksum (0.00s)
    --- PASS: TestCheckpointGetOrCreate/Restore_checkpoint_with_invalid_JSON (0.00s)
=== RUN   TestCheckpointStateStore
--- PASS: TestCheckpointStateStore (0.00s)
PASS
ok      k8s.io/kubernetes/pkg/kubelet/cm/dra/state      (cached)```

**Comment by pohly** [comment]
Thanks!

This will appear in the  next update of the WIP PR as part of the "adapt implementation to new API" commit. I have merged it into my local branch, without pushing just yet.

/close

**Pull request closed without merging**
