### PR TITLE
e2e dra: add new test case

### PR DESCRIPTION
**Pull request by bart0sh**
Test that NodePrepareResource and NodeUnprepareResource are called only once for one claim referenced by multiple containers of a multiple pods.

### CODE REVIEW

**Comment by pohly** [comment]
Can we generalize this check and make sure that all tests have "proper" calls?

"proper" in this case does not mean "exactly one": we just need to check that all claims that were prepared are also unprepared at the end of the test. That it is "exactly one" then can be a special test that is testing for specific kubelet behavior.

**Comment by pohly** [comment]
One possible solution would be to track prepared resources in app/kubeletplugin with an API to query the state, then in tests poll that state.

**Comment by bart0sh** [comment]
> Can we generalize this check and make sure that all tests have "proper" calls?

We can. I'm just worrying it would be a mix of test cases. That's why I decided to make it a separate test case.

**Comment by pohly** [comment]
"Resources were unstaged" is a requirement for all tests. Therefore it makes sense to verify that in all tests.

If we add a test specifically for it, then it is to cover additional scenarios not covered by the others, like force-deleting a pod.

**Comment by bart0sh** [comment]
closing as suggested.

**Comment by pohly** [comment]
> One possible solution would be to track prepared resources in app/kubeletplugin with an API to query the state, then in tests poll that state.

https://github.com/pohly/kubernetes/pull/27 implements that.

**Comment by pohly** [comment]
> closing as suggested.

A test that each function only gets called exactly once still has some value.

**Comment by bart0sh** [comment]
I though that we're going to test that Prepare and Unprepare call count are equal on every test case, no?

**Comment by pohly** [comment]
If we check for equal, then kubelet calling both twice when it should only call them once would not be flagged as a test failure.

**Comment by pohly** [comment]
We cannot test for "exactly once" in the generic code either because a legitimate scenario (in fact, one that we should write a test for) is reusing the same claim in two pods, one after the other.

If we want to test this in the generic code, we would have to parameterize it. We can do that, I'm just a bit worried about the complexity of those parameters.

**Comment by bart0sh** [comment]
either way works for me. I can reopen this PR if needed or we can implement parametrized check for "exactly expected number of PrepareResource and UnprepareResource calls for the test case"

**Pull request closed without merging**
