### PR TITLE
Address review comments for pkg/kubelet/cm/dra/plugin module

### PR DESCRIPTION
**Pull request by bart0sh**

### CODE REVIEW

**Comment by bart0sh** [comment]
@pohly @klueska PTAL

**Comment by klueska** [comment]
LGTM
@pohly feel free to merge

**Comment by bart0sh** [comment]
@pohly rebased and tested. please review & merge

**Comment by pohly** [comment]
Please rebase and squash into a single "fixup! kubelet: add support for dynamic resource allocation" commit.

**Comment by bart0sh** [comment]
@pohly done

**Comment by bart0sh** [comment]
@pohly it looks like you've merged this PR directly into your branch. closing.

**Pull request closed without merging**
