### PR TITLE
Get rid of force pod deletion

### PR DESCRIPTION
**Pull request by bart0sh**
DRA e2e test used force pod deletion for test and plugin pods.
This should not be a default way of deleting pods, but rather an exception.

### CODE REVIEW

**Comment by pohly** [comment]
The commit message is a bit misleading: "used force pod deletion for test and plugin pods."

The delete itself was not using force-deletion. That would have been a DeleteOption with explicit zero as grace period.

It was a bit more indirect: because of the termination grace period being zero, Kubernetes concluded that deletion should also be immediate. It's worth calling that out in the code comment and commit message. A link to https://github.com/kubernetes/kubernetes/blob/0f582f7c3f504e807550310d00f130cb5c18c0c3/pkg/registry/core/pod/strategy.go#L151-L171 would also be useful, for future reference.

**Comment by pohly** [comment]
FWIW, comments in the code are more important than commit message at the moment. Eventually all "e2e dra" commits will be squashed into one, with a commit message that won't capture all details on how the test came into existence.

**Comment by bart0sh** [comment]
The delete itself with a grace period 0 is a force deletion in my understanding.
k8s users are also aware of that I think as kubectl doesn't allow to set grace period 0 without using --force.

**Comment by bart0sh** [comment]
Referirng to https://github.com/kubernetes/kubernetes/blob/0f582f7c3f504e807550310d00f130cb5c18c0c3/pkg/registry/core/pod/strategy.go#L151-L171 would make it harder to understand in my opinion. At least it did it for me until I read this user-friendly explanation: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination-forced.

**Comment by pohly** [comment]
> The delete itself with a grace period 0 is a force deletion in my understanding.

`DeleteOptions.GracePeriodSeconds` is a pointer, therefore `DeleteOptions{}` is not setting `GracePeriodSeconds` to zero. A client has to explicitly choose force deletion, and that was not done here.

**Comment by pohly** [comment]
> Referirng to https://github.com/kubernetes/kubernetes/blob/0f582f7c3f504e807550310d00f130cb5c18c0c3/pkg/registry/core/pod/strategy.go#L151-L171 would make it harder to understand in my opinion. At least it did it for me until I read this user-friendly explanation: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination-forced.

It's okay to refer to both, but the user-facing documentation does not cover the handling of `Spec.TerminationGracePeriodSeconds`, does it? That is only in the code.

**Comment by bart0sh** [comment]
My point was that we shouldn't give too many details on that. Everybody knows that grace period 0 for pod means its force deletion. The change is self-explanatory in my opinion - we don't want force deletion as a default way of deleting pods in our tests. I can change it to whatever you want if you insist, though.

**Comment by pohly** [comment]
> Everybody knows that grace period 0 for pod means its force deletion.

But that's the point: the cleanup code as written at the moment *doesn't* set grace period 0. It's completely unexpected that it force-deleted pods. It only became a force-delete because of some setting elsewhere, and that needs to be explained. Otherwise it remains unclear why `DeleteOptions.GracePeriodSeconds` gets set.

**Comment by pohly** [comment]
A better solution might be to create pods with a 1 second deletion period and not do anything special in the cleanup code.

**Comment by bart0sh** [comment]
ok, closing then

**Pull request closed without merging**
